load("@aspect_rules_buildx//buildx:defs.bzl", "buildx_build")
load("@container_structure_test//:defs.bzl", "container_structure_test")
load("@rules_dotnet//dotnet:defs.bzl", "fsharp_binary", "publish_binary")
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_load")
load("@rules_pkg//:mappings.bzl", "strip_prefix")
load("@rules_pkg//:pkg.bzl", "pkg_tar")

fsharp_binary(
  name = "app",
  srcs = [
    "Program.fs",
  ],
  target_frameworks = [
    "net8.0",
  ],
  deps = [
    "@paket.main//fsharp.core",
  ],
)

publish_binary(
  name = "app-linux-x64",
  binary = ":app",
  target_framework = "net8.0",
  self_contained = True,
  runtime_identifier = "linux-x64",
)

pkg_tar(
  name = "app_files",
  strip_prefix = strip_prefix.from_pkg(),
  package_dir = "/home",
  srcs = [
    ":app-linux-x64",
  ],
  include_runfiles = True,
)

buildx_build(
  name = "base",
  dockerfile = "example/Dockerfile",
  platforms = [
    "linux/amd64",
  ],
)

oci_image(
  name = "image",
  base = ":base",
  entrypoint = [ "/bin/bash", "-c" ],
  cmd = [ "/home/app" ],
  tars = [
    ":app_files",
  ],
)

oci_load(
  name = "tarball",
  image = ":image",
  repo_tags = [
    "bazel/oci_dockerfile_demo:latest",
  ],
)

container_structure_test(
  name = "cst",
  configs = [ "cst.yaml" ],
  image = ":image",
  size = "small",
  target_compatible_with = [
    "@platforms//os:linux",
    "@platforms//cpu:x86_64",
  ],
)
